/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

const maxValue = 4000000

func main() {

  var first, second = 1, 2
  var sum, tmp int

  for {

    // calculate next Fibbonacci number (sum of previous two)
    tmp = second
    second = first + second
    first = tmp
    
    // compute
    if first % 2 == 0 {
      sum += first
    }

    if second > maxValue {
      break
    }

  }

  fmt.Println(first, " ", second)
  fmt.Printf("sum: %d\n", sum)

}