###

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

###

maxValue = 4000000

first = 1
second = 2

sum = 0
tmp = 0

while second < maxValue
	tmp = second
	second = first + second
	first = tmp

	if first % 2 is 0 
		sum += first

console.log "Sum is: #{sum}"