###
Problem 45
Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle     Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
Pentagonal   Pn=n(3n-1)/2      1, 5, 12, 22, 35, ...
Hexagonal    Hn=n(2n-1)        1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
###

_ = require './utils/underscore-min'

tri = []
pen = []
hex = []

count = 0
n     = 2
loop
  tri[n] = n * (n + 1) / 2
  pen[n] = n * (3 * n - 1) / 2
  hex[n] = n * (2 * n - 1)
  if _.contains( pen, tri[n] ) and _.contains( hex, tri[n] )
    console.log "Found T#{n}: #{tri[n]}"
    count++
  if count is 2
    break
  n++