###
Problem 44
Pentagon numbers

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The
first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum
and difference are pentagonal and D = |Pk - Pj| is minimised; what is
the value of D?
###

# x = n*(3n-1)/2 => n = (1 + delta) / 6
# delta = sqrt(24 * x + 1)
isPentagonal = (n) ->
  delta = Math.sqrt(24 * n + 1)
  if delta % 1 isnt 0
    return false
  else
    if delta % 6 isnt 5
      return false
  return true


N = 10000
p = [0] # pentagonals
for n in [1..N]
  p.push n*(3*n-1)/2

for i in [1..N]
  console.log(i) if i % 1000 is 0
  for j in [i+1..N]
    sum = p[i] + p[j]
    dif = Math.abs( p[i] - p[j] )
    if isPentagonal(sum) and isPentagonal(dif)
      console.log p[i], p[j], dif

# empiric 5482660