-- Problem 2

-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

fibGen, fib :: [Integer]
fibGen = 0 : 1 : zipWith (+) fibGen (tail fibGen)
fib = drop 2 fibGen

sumEven :: Integer
-- sumEven = sum [x | x <- fib, x < 4000000, even x ] --> NEVER
sumEven = sum $ takeWhile (< 4000000) $ filter even $ fib

main :: IO ()
main = do
  putStrLn $ show $ sumEven

-- 4613732
