// Generated by CoffeeScript 1.4.0
(function() {

  exports.isPrime = function(n) {
    var i;
    i = 2;
    while ((n !== 1) && (i <= Math.sqrt(n))) {
      if (n % i === 0) {
        return false;
      }
      i++;
    }
    return true;
  };

  exports.divisorSum = function(n) {
    var i, sum, _i, _ref;
    if (n === 2) {
      return 1;
    }
    sum = 1;
    for (i = _i = 2, _ref = Math.ceil(n / 2); 2 <= _ref ? _i <= _ref : _i >= _ref; i = 2 <= _ref ? ++_i : --_i) {
      if (n % i === 0) {
        sum += i;
      }
    }
    return sum;
  };

  exports.hello = function() {
    return 'hello';
  };

}).call(this);
