// Generated by CoffeeScript 1.4.0
(function() {

  exports.isPrime = function(n) {
    var i;
    i = 2;
    while ((n !== 1) && (i <= Math.sqrt(n))) {
      if (n % i === 0) {
        return false;
      }
      i++;
    }
    return true;
  };

  exports.hello = function() {
    return 'hello';
  };

}).call(this);
